# Generated by Django 4.2.1 on 2023-05-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=50)),
                ('StationName', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('choice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bplcNm', models.CharField(max_length=50)),
                ('uptaeNm', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('choice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Convenience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bplcNm', models.CharField(max_length=50)),
                ('siteWhlAddr', models.CharField(max_length=200)),
                ('rdnWhlAddr', models.CharField(max_length=200)),
                ('uptaeNm', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('choose', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bplcNm', models.CharField(max_length=50)),
                ('siteWhlAddr', models.CharField(max_length=200)),
                ('rdnWhlAddr', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('choice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bplcNm', models.CharField(max_length=50)),
                ('siteWhlAddr', models.CharField(max_length=200)),
                ('rdnWhlAddr', models.CharField(max_length=200)),
                ('uptaeNm', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('choice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bplcNm', models.CharField(max_length=50)),
                ('siteWhlAddr', models.CharField(max_length=200)),
                ('rdnWhlAddr', models.CharField(max_length=200)),
                ('uptaeNm', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('choice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bplcNm', models.CharField(max_length=50)),
                ('siteWhlAddr', models.CharField(max_length=200)),
                ('rdnWhlAddr', models.CharField(max_length=200)),
                ('uptaeNm', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('choice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bplcNm', models.CharField(max_length=50)),
                ('siteWhlAddr', models.CharField(max_length=200)),
                ('rdnWhlAddr', models.CharField(max_length=200)),
                ('uptaeNm', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('choice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bplcNm', models.CharField(max_length=50)),
                ('siteWhlAddr', models.CharField(max_length=200)),
                ('rdnWhlAddr', models.CharField(max_length=200)),
                ('uptaeNm', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('choice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('radius', models.IntegerField(null=True)),
            ],
        ),
    ]
